Controllers/QuizzController.cs
using QuizApplicationMVC5.EDMX;
using QuizApplicationMVC5.viewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace QuizApplicationMVC5.Controllers
{
    public class QuizzController : Controller
    {

        public DBQuizEntities dbContext = new DBQuizEntities();

        // GET: Quizz
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetUser(UserVM user)
        {
            UserVM userConnected = dbContext.Users.Where(u => u.FullName == user.FullName)
                                         .Select(u => new UserVM
                                            {
                                                UserID = u.UserID,
                                                FullName = u.FullName,
                                                ProfilImage = u.ProfilImage,

                                            }).FirstOrDefault();

            if(userConnected != null)
            {
                Session["UserConnected"] = userConnected;
                return RedirectToAction("SelectQuizz");
            }
            else
            {
                ViewBag.Msg = "Maaf  : user tidak ditemukan !!";
                return View();
            }

        }

        [HttpGet]
        public ActionResult SelectQuizz()
        {
            QuizVM quiz = new viewModels.QuizVM();
            quiz.ListOfQuizz = dbContext.Quizs.Select(q => new SelectListItem
            {
                Text = q.QuizName,
                Value = q.QuizID.ToString()

            }).ToList();

            return View(quiz);
        }

        [HttpPost]
        public ActionResult SelectQuizz(QuizVM quiz)
        {
            QuizVM quizSelected = dbContext.Quizs.Where(q => q.QuizID == quiz.QuizID).Select(q => new QuizVM
            {
                QuizID = q.QuizID,
                QuizName = q.QuizName,

            }).FirstOrDefault();

            if(quizSelected != null)
            {
                Session["SelectedQuiz"] = quizSelected;

                return RedirectToAction("QuizTest");
            }

            return View();
        }

        [HttpGet]
        public ActionResult QuizTest()
        {
            QuizVM quizSelected = Session["SelectedQuiz"] as QuizVM;
            IQueryable<QuestionVM> questions = null;

            if (quizSelected != null)
            {
                 questions = dbContext.Questions.Where(q => q.Quiz.QuizID == quizSelected.QuizID)
                    .Select(q => new QuestionVM
                    {
                        QuestionID = q.QuestionID,
                        QuestionText = q.QuestionText,
                        Choices = q.Choices.Select(c => new ChoiceVM {
                            ChoiceID = c.ChoiceID,
                            ChoiceText = c.ChoiceText
                        }).ToList()

                    }).AsQueryable();


            }

            return View(questions);
        }

        [HttpPost]
        public ActionResult QuizTest(List<QuizAnswersVM> resultQuiz)
        {
            List<QuizAnswersVM> finalResultQuiz = new List<viewModels.QuizAnswersVM>();

            foreach(QuizAnswersVM answser in resultQuiz)
            {
                QuizAnswersVM result = dbContext.Answers.Where(a => a.QuestionID == answser.QuestionID).Select(a => new QuizAnswersVM
                {
                    QuestionID = a.QuestionID.Value,
                    AnswerQ = a.AnswerText,
                    isCorrect = (answser.AnswerQ.ToLower().Equals(a.AnswerText.ToLower()))

                }).FirstOrDefault();

                finalResultQuiz.Add(result);
            }

            return Json(new { result = finalResultQuiz }, JsonRequestBehavior.AllowGet);
        }


    }
}

Views/Quizz/GetUser.cshtml
@model QuizApplicationMVC5.viewModels.UserVM

@{
    ViewBag.Title = "User";
}

<div class="panel panel-default" style="width: 37%; margin: 20% 32%;">
    <div class="panel-heading">Silakan Login  ^_^</div>
    <div class="panel-body">

        @using (Html.BeginForm("GetUser", "Quizz", FormMethod.Post))
        {
            @Html.EditorFor(c => c.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "FullName ...", @style= "width:100%; margin-left: 56px;" }  } )<br/>
            <button type="submit" id="Enter" class="btn btn-info btn-lg" style="width:100%;"><span class="glyphicon glyphicon-user"></span>   Enter</button>
        }

    </div>

    @if (ViewBag.Msg != null)
    {
        <div class="well well-sm well-danger"> @ViewBag.Msg </div>
    }
</div>

Views/Quizz/QuizTest.cshtml
@model IQueryable<QuizApplicationMVC5.viewModels.QuestionVM>

@{ 
    int count = 1, countR = 0;
}


<div class="container">

   <!-- User Info -->
    <div class="userConnected" style="border:2px dashed #cecaca; border-radius: 10px; margin-top: 3%;">

        @{ Html.RenderPartial("_UserInfo");}

    </div>

    <div class="Quiz">

        <h4 style="margin-top: 4%;"> <span class="label label-info">Questions :</span> </h4>

      @if (Model != null && Model.Any())
      {

              foreach (var question in Model)
              {
                <div class="BlockQ" style="border: 1px solid #bdbdbd; width: 75%; border-radius: 4px; margin-top: 40px; background-color: #f0ffff; padding: 8px;">

                    <div class="Question" style="padding: 2%;">
                        <span class="label label-warning"> @string.Format("{0}{1}.", "Q", count)</span>
                        <span id="@string.Format("{0}{1}", "ID_Q", count)" style="display:none;">@question.QuestionID</span>
                        <p style="display: inline; padding: 2%;" id="@string.Format("{0}{1}", "Q", count)">@question.QuestionText</p>
                    </div>

                    <div class="Choices" style="margin-left: 8%;">

                        @foreach (var choice in question.Choices)
                        {
                                <label class="radio-inline">
                                    <input type="radio" name="@string.Format("{0}{1}", "inlineRadioOptions",count)" id="@string.Format("{0}{1}", "inlineRadio", countR)" value="@choice.ChoiceText" style="margin-left: -16px;"> @choice.ChoiceText
                                </label><br />
                            countR++;
                        }

                    </div> <!--END Choices-->
                 
                <div id="@string.Format("{0}{1}{2}", "Ans","Q", count)">


                </div>

                </div> <!-- END BlockQ -->
                  count++;
              }
            <span id="countQuections" style="display:none;">@count</span>
            <button type="button" id="SubmitQuiz" class="btn btn-default" style="margin-top: 10px;"><span class="glyphicon glyphicon-ok"></span>   Submit Quiz </button>
      

      }

    </div> <!-- END QUIZ -->

</div> <!-- END CONTAINER -->

@section MyScritps
{
    <script type="text/javascript">

        $(document).ready(function () {

            $('#SubmitQuiz').on('click', function () {

                //count Questions
                var sel = $('#countQuections').text();

                console.log(sel);

                var resultQuiz = [], countQuestion = parseInt(sel), question = {}, j = 1;

                for (var i = 1; i < countQuestion; i++) {
                    question = {
                        QuestionID: $('#ID_Q'+ i).text(),
                        QuestionText: $('#Q' + i).text(),
                        AnswerQ: $('input[name=inlineRadioOptions' + i + ']:checked').val()
                    }

                    resultQuiz.push(question);
                }

                $.ajax({

                    type: 'POST',
                    url: '@Url.Action("QuizTest", "Quizz")',
                    data: { resultQuiz },

                    success: function (response) {

                        if (response.result.length > 0)
                        {
                            for(var i = 0; i <response.result.length; i++ )
                            {
                                if(response.result[i].isCorrect == true)
                                {

                                    $('#AnsQ' + j).html('<div class="alert alert-success" role="alert"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Correct answer</div>');
                                }
                                else
                                {
                                    $('#AnsQ' + j).html('<div class="alert alert-danger" role="alert"> <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span> Jawaban Salah - Jawaban Benar : <b>' + response.result[i].AnswerQ + '</b></div>');
                                }
                                j++;
                            }
                        }
                        else
                        {
                            alert("Something Wrong");
                        }


                        //console.log(response.result.length);

                    },
                    error: function (response) {

                    }
                });

                console.log(resultQuiz);

            });



        });

    </script>
}

Views/Quizz/SelectQuizz.cshtml
@model QuizApplicationMVC5.viewModels.QuizVM

@{
    ViewBag.Title = "SelectQuizz";
}

<div class="container">

    <div class="userConnected" style="border:2px dashed #cecaca; border-radius: 10px; margin-top: 3%;">

        @{ Html.RenderPartial("_UserInfo");}

    </div>


    <div class="SelQuiz">

        <div class="panel panel-default" style="width: 37%; margin: 20% 32%;">
            <div class="panel-heading">Pilih Quiz mu</div>
            <div class="panel-body">

                @using (Html.BeginForm("SelectQuizz", "Quizz", FormMethod.Post))
                {
                    @Html.DropDownListFor(model => model.QuizID, Model.ListOfQuizz, new { @class = "form-control", @style = "margin-left:51px;" } )<br/>
                    <button type="submit" id="Enter" class="btn btn-success btn-lg" style="width:100%;"><span class="glyphicon glyphicon-ok"></span>   Mulai Quiz ini </button>
                }

            </div>
        </div>

    </div>

</div>  <!-- END CONTAINER -->